// Constantes para os códigos dos campos de configuração de portais

// Configurações Gerais
export const PORTAL_SETTINGS_CODES = {
  // Configurações Gerais
  PORTAL_DESCRICAO_PADRAO: 'PORTAL_DESCRICAO_PADRAO',
  PORTAL_MINIMO_FOTOS: 'PORTAL_MINIMO_FOTOS',
  PORTAL_VIDEO_PADRAO: 'PORTAL_VIDEO_PADRAO',
  PORTAL_TOUR_360_PADRAO: 'PORTAL_TOUR_360_PADRAO',
  PORTAL_ENDERECO_TIPO: 'PORTAL_ENDERECO_TIPO',
  PORTAL_AGRUPAR_SIMILARES: 'PORTAL_AGRUPAR_SIMILARES',
  PORTAL_NAO_ENVIAR_CEP_ZERADO: 'PORTAL_NAO_ENVIAR_CEP_ZERADO',
  PORTAL_PREENCHER_AREA_UTIL_AUTO: 'PORTAL_PREENCHER_AREA_UTIL_AUTO',
  PORTAL_ORDENAR_POR_MAIOR_VALOR: 'PORTAL_ORDENAR_POR_MAIOR_VALOR',
  PORTAL_ENVIAR_APENAS_VENDAS: 'PORTAL_ENVIAR_APENAS_VENDAS',
  PORTAL_ENVIAR_APENAS_LANCAMENTOS_RI: 'PORTAL_ENVIAR_APENAS_LANCAMENTOS_RI',
  PORTAL_ENVIAR_APENAS_MEUS_IMOVEIS: 'PORTAL_ENVIAR_APENAS_MEUS_IMOVEIS',
  PORTAL_NAO_ENVIAR_LANCAMENTOS: 'PORTAL_NAO_ENVIAR_LANCAMENTOS',
  PORTAL_USAR_REF_ALTERNATIVA: 'PORTAL_USAR_REF_ALTERNATIVA',
  PORTAL_ALTERNAR_PRECO_SEMANAL: 'PORTAL_ALTERNAR_PRECO_SEMANAL',
  PORTAL_PORCENTAGEM_AUMENTO_PRECO: 'PORTAL_PORCENTAGEM_AUMENTO_PRECO',
  PORTAL_KITNET_COMO_UM_DORMITORIO: 'PORTAL_KITNET_COMO_UM_DORMITORIO',
  PORTAL_ENVIAR_VALOR_ENTRADA: 'PORTAL_ENVIAR_VALOR_ENTRADA',

  // Configurações por Portal - Imóvel Web
  PORTAL_IMOVEL_WEB__HABILITADO: 'PORTAL_IMOVEL_WEB__HABILITADO',
  PORTAL_IMOVEL_WEB__QTD_ENVIAR: 'PORTAL_IMOVEL_WEB__QTD_ENVIAR',
  PORTAL_IMOVEL_WEB__QTD_DESTAQUE: 'PORTAL_IMOVEL_WEB__QTD_DESTAQUE',
  PORTAL_IMOVEL_WEB__QTD_SUPER_DESTAQUE: 'PORTAL_IMOVEL_WEB__QTD_SUPER_DESTAQUE',
  PORTAL_IMOVEL_WEB__ENVIO_AUTOMATICO: 'PORTAL_IMOVEL_WEB__ENVIO_AUTOMATICO',
  PORTAL_IMOVEL_WEB__ENVIAR_TODOS: 'PORTAL_IMOVEL_WEB__ENVIAR_TODOS',

  // Configurações por Portal - Canal Pro
  PORTAL_CANAL_PRO__HABILITADO: 'PORTAL_CANAL_PRO__HABILITADO',
  PORTAL_CANAL_PRO__QTD_ENVIAR: 'PORTAL_CANAL_PRO__QTD_ENVIAR',
  PORTAL_CANAL_PRO__QTD_DESTAQUE: 'PORTAL_CANAL_PRO__QTD_DESTAQUE',
  PORTAL_CANAL_PRO__QTD_SUPER_DESTAQUE: 'PORTAL_CANAL_PRO__QTD_SUPER_DESTAQUE',
  PORTAL_CANAL_PRO__ENVIO_AUTOMATICO: 'PORTAL_CANAL_PRO__ENVIO_AUTOMATICO',
  PORTAL_CANAL_PRO__ENVIAR_TODOS: 'PORTAL_CANAL_PRO__ENVIAR_TODOS',

  // Configurações por Portal - MGF Imóveis
  PORTAL_PMGF__HABILITADO: 'PORTAL_PMGF__HABILITADO',
  PORTAL_PMGF__QTD_ENVIAR: 'PORTAL_PMGF__QTD_ENVIAR',
  PORTAL_PMGF__QTD_DESTAQUE: 'PORTAL_PMGF__QTD_DESTAQUE',
  PORTAL_PMGF__QTD_SUPER_DESTAQUE: 'PORTAL_PMGF__QTD_SUPER_DESTAQUE',
  PORTAL_PMGF__ENVIO_AUTOMATICO: 'PORTAL_PMGF__ENVIO_AUTOMATICO',
  PORTAL_PMGF__ENVIAR_TODOS: 'PORTAL_PMGF__ENVIAR_TODOS',

  // Configurações por Portal - SP Imóveis
  PORTAL_LITORAL_HABILITADO: 'PORTAL_LITORAL_HABILITADO',
  PORTAL_LITORAL_QTD_ENVIAR: 'PORTAL_LITORAL_QTD_ENVIAR',
  PORTAL_LITORAL_QTD_DESTAQUE: 'PORTAL_LITORAL_QTD_DESTAQUE',
  PORTAL_LITORAL_QTD_SUPER_DESTAQUE: 'PORTAL_LITORAL_QTD_SUPER_DESTAQUE',
  PORTAL_LITORAL_ENVIO_AUTOMATICO: 'PORTAL_LITORAL_ENVIO_AUTOMATICO',
  PORTAL_LITORAL_ENVIAR_TODOS: 'PORTAL_LITORAL_ENVIAR_TODOS',

  // Configurações por Portal - 123i
  PORTAL_123I__HABILITADO: 'PORTAL_123I__HABILITADO',
  PORTAL_123I__QTD_ENVIAR: 'PORTAL_123I__QTD_ENVIAR',
  PORTAL_123I__QTD_DESTAQUE: 'PORTAL_123I__QTD_DESTAQUE',
  PORTAL_123I__QTD_SUPER_DESTAQUE: 'PORTAL_123I__QTD_SUPER_DESTAQUE',
  PORTAL_123I__ENVIO_AUTOMATICO: 'PORTAL_123I__ENVIO_AUTOMATICO',
  PORTAL_123I__ENVIAR_TODOS: 'PORTAL_123I__ENVIAR_TODOS',

  // Configurações por Portal - Imóvel Guide
  PORTAL_IMOVEL_GUIDE__HABILITADO: 'PORTAL_IMOVEL_GUIDE__HABILITADO',
  PORTAL_IMOVEL_GUIDE__QTD_ENVIAR: 'PORTAL_IMOVEL_GUIDE__QTD_ENVIAR',
  PORTAL_IMOVEL_GUIDE__QTD_DESTAQUE: 'PORTAL_IMOVEL_GUIDE__QTD_DESTAQUE',
  PORTAL_IMOVEL_GUIDE__QTD_SUPER_DESTAQUE: 'PORTAL_IMOVEL_GUIDE__QTD_SUPER_DESTAQUE',
  PORTAL_IMOVEL_GUIDE__ENVIO_AUTOMATICO: 'PORTAL_IMOVEL_GUIDE__ENVIO_AUTOMATICO',
  PORTAL_IMOVEL_GUIDE__ENVIAR_TODOS: 'PORTAL_IMOVEL_GUIDE__ENVIAR_TODOS',

  // Configurações por Portal - Dream Casa
  PORTAL_DREAM_CASA__HABILITADO: 'PORTAL_DREAM_CASA__HABILITADO',
  PORTAL_DREAM_CASA__QTD_ENVIAR: 'PORTAL_DREAM_CASA__QTD_ENVIAR',
  PORTAL_DREAM_CASA__QTD_DESTAQUE: 'PORTAL_DREAM_CASA__QTD_DESTAQUE',
  PORTAL_DREAM_CASA__QTD_SUPER_DESTAQUE: 'PORTAL_DREAM_CASA__QTD_SUPER_DESTAQUE',
  PORTAL_DREAM_CASA__ENVIO_AUTOMATICO: 'PORTAL_DREAM_CASA__ENVIO_AUTOMATICO',
  PORTAL_DREAM_CASA__ENVIAR_TODOS: 'PORTAL_DREAM_CASA__ENVIAR_TODOS',

  // Configurações por Portal - Homer
  PORTAL_HOMER__HABILITADO: 'PORTAL_HOMER__HABILITADO',
  PORTAL_HOMER__QTD_ENVIAR: 'PORTAL_HOMER__QTD_ENVIAR',
  PORTAL_HOMER__QTD_DESTAQUE: 'PORTAL_HOMER__QTD_DESTAQUE',
  PORTAL_HOMER__QTD_SUPER_DESTAQUE: 'PORTAL_HOMER__QTD_SUPER_DESTAQUE',
  PORTAL_HOMER__ENVIO_AUTOMATICO: 'PORTAL_HOMER__ENVIO_AUTOMATICO',
  PORTAL_HOMER__ENVIAR_TODOS: 'PORTAL_HOMER__ENVIAR_TODOS',

  // Configurações por Portal - Buskaza
  PORTAL_BUSKAZA__HABILITADO: 'PORTAL_BUSKAZA__HABILITADO',
  PORTAL_BUSKAZA__QTD_ENVIAR: 'PORTAL_BUSKAZA__QTD_ENVIAR',
  PORTAL_BUSKAZA__QTD_DESTAQUE: 'PORTAL_BUSKAZA__QTD_DESTAQUE',
  PORTAL_BUSKAZA__QTD_SUPER_DESTAQUE: 'PORTAL_BUSKAZA__QTD_SUPER_DESTAQUE',
  PORTAL_BUSKAZA__ENVIO_AUTOMATICO: 'PORTAL_BUSKAZA__ENVIO_AUTOMATICO',
  PORTAL_BUSKAZA__ENVIAR_TODOS: 'PORTAL_BUSKAZA__ENVIAR_TODOS',

  // Configurações por Portal - CreciSP
  PORTAL_CRECI__HABILITADO: 'PORTAL_CRECI__HABILITADO',
  PORTAL_CRECI__QTD_ENVIAR: 'PORTAL_CRECI__QTD_ENVIAR',
  PORTAL_CRECI__QTD_DESTAQUE: 'PORTAL_CRECI__QTD_DESTAQUE',
  PORTAL_CRECI__QTD_SUPER_DESTAQUE: 'PORTAL_CRECI__QTD_SUPER_DESTAQUE',
  PORTAL_CRECI__ENVIO_AUTOMATICO: 'PORTAL_CRECI__ENVIO_AUTOMATICO',
  PORTAL_CRECI__ENVIAR_TODOS: 'PORTAL_CRECI__ENVIAR_TODOS',

  // Configurações por Portal - Chaves na Mão
  PORTAL_CHAVES_NA_MAO__HABILITADO: 'PORTAL_CHAVES_NA_MAO__HABILITADO',
  PORTAL_CHAVES_NA_MAO__QTD_ENVIAR: 'PORTAL_CHAVES_NA_MAO__QTD_ENVIAR',
  PORTAL_CHAVES_NA_MAO__QTD_DESTAQUE: 'PORTAL_CHAVES_NA_MAO__QTD_DESTAQUE',
  PORTAL_CHAVES_NA_MAO__QTD_SUPER_DESTAQUE: 'PORTAL_CHAVES_NA_MAO__QTD_SUPER_DESTAQUE',
  PORTAL_CHAVES_NA_MAO__ENVIO_AUTOMATICO: 'PORTAL_CHAVES_NA_MAO__ENVIO_AUTOMATICO',
  PORTAL_CHAVES_NA_MAO__ENVIAR_TODOS: 'PORTAL_CHAVES_NA_MAO__ENVIAR_TODOS',

  // Configurações por Portal - CasaMineira
  PORTAL_CASA_MINEIRA__HABILITADO: 'PORTAL_CASA_MINEIRA__HABILITADO',
  PORTAL_CASA_MINEIRA__QTD_ENVIAR: 'PORTAL_CASA_MINEIRA__QTD_ENVIAR',
  PORTAL_CASA_MINEIRA__QTD_DESTAQUE: 'PORTAL_CASA_MINEIRA__QTD_DESTAQUE',
  PORTAL_CASA_MINEIRA__QTD_SUPER_DESTAQUE: 'PORTAL_CASA_MINEIRA__QTD_SUPER_DESTAQUE',
  PORTAL_CASA_MINEIRA__ENVIO_AUTOMATICO: 'PORTAL_CASA_MINEIRA__ENVIO_AUTOMATICO',
  PORTAL_CASA_MINEIRA__ENVIAR_TODOS: 'PORTAL_CASA_MINEIRA__ENVIAR_TODOS',

  // Configurações por Portal - Compre&Alugue
  PORTAL_COMPRE_ALUGUE__HABILITADO: 'PORTAL_COMPRE_ALUGUE__HABILITADO',
  PORTAL_COMPRE_ALUGUE__QTD_ENVIAR: 'PORTAL_COMPRE_ALUGUE__QTD_ENVIAR',
  PORTAL_COMPRE_ALUGUE__QTD_DESTAQUE: 'PORTAL_COMPRE_ALUGUE__QTD_DESTAQUE',
  PORTAL_COMPRE_ALUGUE__QTD_SUPER_DESTAQUE: 'PORTAL_COMPRE_ALUGUE__QTD_SUPER_DESTAQUE',
  PORTAL_COMPRE_ALUGUE__ENVIO_AUTOMATICO: 'PORTAL_COMPRE_ALUGUE__ENVIO_AUTOMATICO',
  PORTAL_COMPRE_ALUGUE__ENVIAR_TODOS: 'PORTAL_COMPRE_ALUGUE__ENVIAR_TODOS',
} as const;

// Mapeamento dos IDs dos portais para os códigos
export const PORTAL_ID_TO_CODE_MAP = {
  'imovelweb': 'IMOVEL_WEB',
  'canal-pro': 'CANAL_PRO',
  'mgf-imoveis': 'PMGF',
  'sp-imoveis': 'LITORAL',
  '123i': '123I',
  'imovel-guide': 'IMOVEL_GUIDE',
  'dream-casa': 'DREAM_CASA',
  'homer': 'HOMER',
  'buskaza': 'BUSKAZA',
  'creci-sp': 'CRECI',
  'chaves-na-mao': 'CHAVES_NA_MAO',
  'casa-mineira': 'CASA_MINEIRA',
  'compre-alugue': 'COMPRE_ALUGUE',
} as const;

// Função para gerar código do portal
export function getPortalCode(portalId: string, field: string): string {
  const portalCode = PORTAL_ID_TO_CODE_MAP[portalId as keyof typeof PORTAL_ID_TO_CODE_MAP];
  return `PORTAL_${portalCode}__${field}`;
} 